on:
  push:
    branches: [ dev, feature/* ]
name: "Deploy Dev APK"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Signing Properties
        run: |
          cd mapp
          echo ${{ secrets.BASE64_KEYSTORE }} | base64 -d > keystore.jks
          ls
          cd ..
          ls
          echo "" > signing.properties
          echo "release.keystore=keystore.jks" >> signing.properties
          echo "release.keystore.alias=${{ vars.KEYSTORE_ALIAS }}" >> signing.properties
          echo "release.keystore.keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> signing.properties
          echo "release.keystore.storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> signing.properties
          cat signing.properties